language: java
jdk: openjdk7
env:
  global:
    - TERM=dumb
    - secure: "G55cianauQx3GwNroQocl0I6ZFtulxOtKpYR8f3s3G9a8rfJImByq0k7LxIwWTS3F/Fsv5pngW4GzQLQUhkX5GPEL0c3lM8m8y1Yn2ldxXIwUpS5B4fsfO9hF1iLgbnzDOPC5ujb6POt8DPadPjm7+vTwWxizhq51y/rUGBJ15k="
    - secure: "XnChH/eMk7tmXe24Bcrnj3t8L1559gkb20efZPXI/9Vvlcnnmw6oG7UT2ecYouTWw5ph1wxmL3r8doIhq+Zwgg8WoO/8bTU0kpQFNwYgbfYU+iMuPI6WM9VNFbxxsmqT+Rl/fuma3ckw+npRYvSRGTGXqAhhUNt5fHCM3t3KQuc="
script:
  - ./gradlew clean build --stacktrace --info
after_success:
  - ./gradlew bintrayUpload -x check --info
